In [1]:
#Importing the important libraries
import pandas as pd
from bs4 import BeautifulSoup as soup
import requests
import time

In [2]:
#Web Scrapping main function
# def web_scrapping(page):
#     page_soup = soup(page.text, 'html.parser')                     #Parsing the large HTML file
#     containers = page_soup.findAll("div", {"class" : "_3liAhj"})   #Find all div tags which is a class and name of div tag:_3liAhj

#     for container in containers:
#         #Grabbing product name
#         product_name = container.findAll("a",{"class" : "_2cLu-l"})
#         product = product_name[0].text
        
#         #Fetching brand name
#         temp = product.split(" ")
#         if len(temp) <= 3:                  #Taking care of brands like "Dr. Oetker"
#             brand = temp[0] + " " + temp[1]
#         else:
#             brand = temp[0]
        
#         #Grabbing product discounted price and applying string manipulation to clean the data
#         discounted_price_container =  container.findAll("div", {"class" : "_1vC4OE"})
#         if len(discounted_price_container) == 0:
#             final_discounted_price = 'NA'
#         else:
#             discounted_price = discounted_price_container[0].text.strip()
#             split_price = discounted_price.split('₹')
#             final_discounted_price = 'Rs.' + split_price[1]
        
#         #Grabbing % of dicount offered and applying string manipulation to clean the data
#         discount_container = container.findAll("div", {"class" : "VGWI6T"})
#         if len(discount_container) == 0:
#             final_discount = '0%'
#         else:
#             discount = discount_container[0].text.split(" ")
#             final_discount = discount[0]
        
#         #Grabbing original price and applying string manipulation to clean the data
#         original_price_container =  container.findAll("div", {"class" : "_3auQ3N"})
#         if len(original_price_container) == 0:
#             final_original_price = final_discounted_price
#         else:
#             original_price = original_price_container[0].text.strip()
#             split_original_price = original_price.split('₹')
#             final_original_price = 'Rs.' + split_original_price[1]
        
#         #Grabbing product rating and applying string manipulation to clean the data
#         rating_container = container.findAll("div", {"class" : "hGSR34"})
#         if len(rating_container) == 0:
#             final_rating = 'NA'
#         else:
#             rating = rating_container[0].text
#             split_rating = rating.split('(')
#             final_rating = split_rating[0]
        
#         #Grabbing total number of ratings done by people and applying string manipulation to clean the data
#         total_ratings_by_people = container.findAll("span", {"class" : "_38sUEc"})
#         if len(total_ratings_by_people) == 0:
#             total_ratings = "NA"
#         else:
#             total_ratings = total_ratings_by_people[0].text
#             total_ratings = total_ratings[1:len(total_ratings)-1]
            
#         #Grabbing product urls
#         temp_product_url_container =  container.find("a", {"class" : '_2cLu-l'})['href']
#         product_url_container = 'https://www.flipkart.com' + temp_product_url_container
        
#         #Appending data to their respective lists
#         Product_name.append(product)
#         Brand.append(brand)
#         Discounted_Price.append(final_discounted_price)
#         Discount.append(final_discount)
#         Original_Price.append(final_original_price)
#         Ratings.append(final_rating)
#         Total_Ratings.append(total_ratings)
#         Product_URL.append(product_url_container)

In [3]:
#Connection establishment function to establish a connection to the mentioned URL
# def connection_establishment(page_number,url):
#         page = requests.get(search_url)
#         if page.status_code == requests.codes.ok:           #Checking the response code as 200 then proceeding for scrapping
#             print(f'Connection succeeded with {page_number} URL')
#             try:
#                 web_scrapping(page)
#             except:
#                 print('Something went wrong! Retrying scrapping from the next page')
                
#         else:
#             print('Connection failed')                     #In case 200 response not received

In [4]:
# #Some declarations 
# page_number = 1                 #Initialising page number to start with
# starting_page_index = 1         #Starting page to start scrapping 
# ending_page_index = 200       #Ending page to end scrapping 

# Product_name = []
# Brand = []
# Discounted_Price = []
# Discount = []
# Original_Price = []
# Ratings = []
# Total_Ratings = []
# Product_URL = []

# for i in range(starting_page_index,ending_page_index):     
#     search_url = f'https://www.flipkart.com/food-nutrition/pr?sid=7jv&marketplace=FLIPKART&page='+ str(page_number)
#     connection_establishment(page_number,search_url)
#     time.sleep(10)              #Sleeping forced to prevent multiple requests flood on the website
#     page_number += 1

# #Creating a dataframe
# groceries = pd.DataFrame(
# {
#     'Product_name' : Product_name,
#     'Brand' : Brand,
#     'Discounted_Price' : Discounted_Price,
#     'Discount' : Discount,
#     'Original_Price' : Original_Price,
#     'Ratings' : Ratings,
#     'Total_Ratings' : Total_Ratings,
#     'Product_URL' : Product_URL,
# })

# #Resetting index to start from 1
# groceries.index = groceries.index + 1
# print(groceries)

# #Exporting to a csv file
# groceries.to_csv('flipkart_web_scrapped_data.csv', encoding='utf-8')

In [5]:
#Importing the data
df = pd.read_csv("flipkart_web_scrapped_data.csv",index_col=0)  
df.head()       #Checking top 5 rows

,Product_name,Brand,Discounted_Price,Discount,Original_Price,Ratings,Total_Ratings,Product_URL
1,Cadbury Bournvita Health Drink Nutrition Drink,Cadbury,Rs.286,1%,Rs.290,4.5,"11,923",https://www.flipkart.com/cadbury-bournvita-hea...
2,Betty Crocker Triple Choco Brownie Mix 425 g,Betty,Rs.322,2%,Rs.330,4.4,294,https://www.flipkart.com/betty-crocker-triple-...
3,Madhur Sugar,Madhur Sugar,Rs.48,12%,Rs.55,4.5,"17,460",https://www.flipkart.com/madhur-sugar/p/itmevj...
4,Tata Iodized Salt,Tata Iodized,Rs.20,0%,Rs.20,4.6,"7,287",https://www.flipkart.com/tata-iodized-salt/p/i...
5,Roxy Gold Maida,Roxy Gold,Rs.55,0%,Rs.55,4.4,"1,828",https://www.flipkart.com/roxy-gold-maida/p/itm...

In [6]:
#Printing total rows and columns and also having a glance at the data types
print(df.shape)
df.info()

(1000, 8)
<class 'pandas.core.frame.DataFrame'>
Int64Index: 1000 entries, 1 to 1000
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Product_name      1000 non-null   object
 1   Brand             1000 non-null   object
 2   Discounted_Price  1000 non-null   object
 3   Discount          1000 non-null   object
 4   Original_Price    1000 non-null   object
 5   Ratings           922 non-null    float64
 6   Total_Ratings     922 non-null    object
 7   Product_URL       1000 non-null   object
dtypes: float64(1), object(7)
memory usage: 70.3+ KB

In [7]:
#Dropping the prefix 'Rs.' from column Original_Price, Discounted_Price.
#Dropping suffix '%' from the rows of column Discount.

df.Original_Price = df.Original_Price.str.replace("Rs.","").str.replace(",","")
df.Discounted_Price = df.Discounted_Price.str.replace("Rs.","").str.replace(",","")
df.Discount = df.Discount.str.replace("%","")
df.Total_Ratings = df.Total_Ratings.str.replace(",","")

#Printing top five rows to have a glance at the modification applied
df.head()

,Product_name,Brand,Discounted_Price,Discount,Original_Price,Ratings,Total_Ratings,Product_URL
1,Cadbury Bournvita Health Drink Nutrition Drink,Cadbury,286,1,290,4.5,11923,https://www.flipkart.com/cadbury-bournvita-hea...
2,Betty Crocker Triple Choco Brownie Mix 425 g,Betty,322,2,330,4.4,294,https://www.flipkart.com/betty-crocker-triple-...
3,Madhur Sugar,Madhur Sugar,48,12,55,4.5,17460,https://www.flipkart.com/madhur-sugar/p/itmevj...
4,Tata Iodized Salt,Tata Iodized,20,0,20,4.6,7287,https://www.flipkart.com/tata-iodized-salt/p/i...
5,Roxy Gold Maida,Roxy Gold,55,0,55,4.4,1828,https://www.flipkart.com/roxy-gold-maida/p/itm...

In [8]:
#Checking for null or missing values in my data
df.isnull().sum()

Product_name         0
Brand                0
Discounted_Price     0
Discount             0
Original_Price       0
Ratings             78
Total_Ratings       78
Product_URL          0
dtype: int64

In [9]:
#Replacing Nan values with zero
df["Total_Ratings"] = df["Total_Ratings"].fillna(0)
df["Ratings"] = df["Ratings"].fillna(0)

In [10]:
#Changing data types for column Discounted_Price, Discount, Original_Price
convert_dict = {'Discounted_Price' : float, 
                'Discount' : float,
                'Original_Price' : float,
                'Total_Ratings' : int,
               }

df = df.astype(convert_dict) 
print(df.info())

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1000 entries, 1 to 1000
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Product_name      1000 non-null   object
 1   Brand             1000 non-null   object
 2   Discounted_Price  1000 non-null   float64
 3   Discount          1000 non-null   float64
 4   Original_Price    1000 non-null   float64
 5   Ratings           1000 non-null   float64
 6   Total_Ratings     1000 non-null   int64
 7   Product_URL       1000 non-null   object
dtypes: float64(4), int64(1), object(3)
memory usage: 70.3+ KB
None

In [11]:
#Checking for null or missing values in my data
df.isnull().sum()

Product_name        0
Brand               0
Discounted_Price    0
Discount            0
Original_Price      0
Ratings             0
Total_Ratings       0
Product_URL         0
dtype: int64

In [12]:
#Checking for incorrect discount price calculations
incorrect_values_container = []
for ind in df.index:
    cal = df['Original_Price'][ind] - (df['Original_Price'][ind] * df['Discount'][ind])
    if cal == df['Discounted_Price'][ind]:
        incorrect_values_container.append(ind)
print(incorrect_values_container)
print("Total discrepancies found: ",len(incorrect_values_container))

[4, 5, 13, 19, 21, 22, 31, 53, 69, 75, 97, 103, 106, 112, 113, 122, 132, 133, 141, 143, 146, 147, 156, 157, 183, 188, 189, 193, 201, 219, 225, 230, 231, 240, 255, 258, 265, 272, 273, 283, 297, 298, 307, 313, 343, 379, 385, 386, 394, 400, 418, 428, 489, 496, 501, 502, 510, 518, 520, 526, 536, 547, 559, 562, 586, 589, 615, 632, 657, 666, 681, 698, 713, 721, 725, 741, 752, 765, 767, 783, 828, 855, 863, 903, 921, 946, 952, 955, 957, 986, 988]
Total discrepancies found:  91

In [13]:
#Dropping these records from df
print("Total records before dropping incorrect data of rows: ",df.shape[0])

df = df.drop(incorrect_values_container, axis=0)

print("Total records after dropping incorrect data of rows: ",df.shape[0])

Total records before dropping incorrect data of rows:  1000
Total records after dropping incorrect data of rows:  909

In [14]:
df.reset_index(inplace = True, drop = True)    #Resetting the indices
df.index = df.index + 1 
df

,Product_name,Brand,Discounted_Price,Discount,Original_Price,Ratings,Total_Ratings,Product_URL
1,Cadbury Bournvita Health Drink Nutrition Drink,Cadbury,286.0,1.0,290.0,4.5,11923,https://www.flipkart.com/cadbury-bournvita-hea...
2,Betty Crocker Triple Choco Brownie Mix 425 g,Betty,322.0,2.0,330.0,4.4,294,https://www.flipkart.com/betty-crocker-triple-...
3,Madhur Sugar,Madhur Sugar,48.0,12.0,55.0,4.5,17460,https://www.flipkart.com/madhur-sugar/p/itmevj...
4,Fortune Sunlite Refined Sunflower Oil Can,Fortune,591.0,13.0,685.0,4.5,1660,https://www.flipkart.com/fortune-sunlite-refin...
5,Emami Healthy & Tasty Kachchi Ghani Mustard Oi...,Emami,133.0,14.0,155.0,4.4,1138,https://www.flipkart.com/emami-healthy-tasty-k...
...,...,...,...,...,...,...,...,...
905,Optimum Nutrition Gold Standard 100% Casein Pr...,Optimum,5549.0,25.0,7399.0,4.3,166,https://www.flipkart.com/optimum-nutrition-gol...
906,"NAVVAYD Strawberry Mango Tea (50 Cups), 100% N...",NAVVAYD,349.0,22.0,449.0,4.2,38,https://www.flipkart.com/navvayd-strawberry-ma...
907,Nescafe Azera Intenso Instant Coffee with Grou...,Nescafe,999.0,33.0,1499.0,0.0,0,https://www.flipkart.com/nescafe-azera-intenso...
908,N2B Organic Green Coffee Beans Powder with Lem...,N2B,303.0,74.0,1199.0,4.4,5,https://www.flipkart.com/n2b-organic-green-cof...
909,Saffola Fittify Gourmet Slim Meal Shake Whey P...,Saffola,1038.0,12.0,1190.0,4.3,86,https://www.flipkart.com/saffola-fittify-gourm...

In [15]:
#Checking for duplicates 
df.Product_name.value_counts()

Cadbury Bournvita Health Drink Nutrition Drink                23
Tang Mango Instant Drink Mix                                  22
Cadbury Bournvita Inner Strength Nutrition Drink              22
Tang Orange Instant Drink Mix                                 22
Betty Crocker Triple Choco Brownie Mix 425 g                  22
                                                              ..
D NATURE FRESH Roasted & Salted Almonds 250g (Pouch) Al...     1
Nescafe Classic Pure Soluble Coffee - 200g Instant Coff...     1
SHRI ANAND Red Chilli Flakes (Mirch Kuti )                     1
TE-A-ME Pack of 2 Five Delicious Flavours with Sipper L...     1
Madhur Sugar                                                   1
Name: Product_name, Length: 699, dtype: int64

In [16]:
df.drop_duplicates("Product_name",inplace=True)
df.reset_index(drop=True,inplace=True)
df.index = df.index + 1 
print("Total records after dropping duplicates: ",df.shape[0])

Total records after dropping duplicates:  699

In [17]:
print('Final cleaned dataset obtained: ')
df

Final cleaned dataset obtained:

,Product_name,Brand,Discounted_Price,Discount,Original_Price,Ratings,Total_Ratings,Product_URL
1,Cadbury Bournvita Health Drink Nutrition Drink,Cadbury,286.0,1.0,290.0,4.5,11923,https://www.flipkart.com/cadbury-bournvita-hea...
2,Betty Crocker Triple Choco Brownie Mix 425 g,Betty,322.0,2.0,330.0,4.4,294,https://www.flipkart.com/betty-crocker-triple-...
3,Madhur Sugar,Madhur Sugar,48.0,12.0,55.0,4.5,17460,https://www.flipkart.com/madhur-sugar/p/itmevj...
4,Fortune Sunlite Refined Sunflower Oil Can,Fortune,591.0,13.0,685.0,4.5,1660,https://www.flipkart.com/fortune-sunlite-refin...
5,Emami Healthy & Tasty Kachchi Ghani Mustard Oi...,Emami,133.0,14.0,155.0,4.4,1138,https://www.flipkart.com/emami-healthy-tasty-k...
...,...,...,...,...,...,...,...,...
695,Midiron 100 % Natural Premium Raisin/kishmish ...,Midiron,239.0,20.0,299.0,4.3,6,https://www.flipkart.com/midiron-100-natural-p...
696,Herbal Vibe Pure Shilajit Extract Capsules to ...,Herbal,484.0,39.0,799.0,4.2,13,https://www.flipkart.com/herbal-vibe-pure-shil...
697,"NAVVAYD Strawberry Mango Tea (50 Cups), 100% N...",NAVVAYD,349.0,22.0,449.0,4.2,38,https://www.flipkart.com/navvayd-strawberry-ma...
698,Nescafe Azera Intenso Instant Coffee with Grou...,Nescafe,999.0,33.0,1499.0,0.0,0,https://www.flipkart.com/nescafe-azera-intenso...
699,N2B Organic Green Coffee Beans Powder with Lem...,N2B,303.0,74.0,1199.0,4.4,5,https://www.flipkart.com/n2b-organic-green-cof...

In [20]:
# Finally adding a column for platform.
df['Platform']='Flipkart'

In [21]:
# For the ease sake and to work with other's data, creating one more csv for integration.
df.to_csv('Flipkart_data_cleaned.csv', index=False, header=True)